docs/faq.md

Updated from "changelog" to "Changelog"

Fixed link to Changelog

---

src/dndbeyond.pyj
src/dndbeyond_character.pyj
src/dndbeyond_dice.pyj
src/roll20.pyj
src/settings.pyj

Add dex score tiebreaker to initiative

---

src/dndbeyond.pyj

Disable HP syncing from D&D Beyond if disabled

---

src/dndbeyond_character.js
src/dndbeyond_character.pyj
src/dndbeyond_encounter.js
src/dndbeyond_items.js
src/dndbeyond_monster.js
src/dndbeyond_spell.js
src/dndbeyond_vehicle.js
src/fvtt_script.js
src/roll20.js
src/roll20.pyj
src/roll_renderer.pyj

Added support for Ranger ability "Hunter Slayer"

Ranger special ability support

---

src/dndbeyond.pyj
src/dndbeyond_character.js
src/dndbeyond_discord.pyj
src/dndbeyond_encounter.js
src/dndbeyond_items.js
src/dndbeyond_monster.js
src/dndbeyond_spell.js
src/dndbeyond_vehicle.js
src/fvtt_script.js

When selected to "Whisper rolls" or to "Hide monster names and attacks", the monster name and attack name will be obfuscated
fixes #189 - adds link to character sheet (unless hidden by whisper)

Discord - Hide monster names and attacks

---

src/background.js
src/default_popup.js
src/dndbeyond.pyj
src/dndbeyond_character.js
src/dndbeyond_encounter.js
src/dndbeyond_items.js
src/dndbeyond_monster.js
src/dndbeyond_spell.js
src/dndbeyond_vehicle.js
src/fvtt.js
src/fvtt_script.js
src/options.js
src/popup.js
src/roll20.js
src/roll20_script.js
src/utils.pyj

Added support to clean roll strings for various imperfections due to edge case formatting in some abilities (Monk's deflect missiles)
fixes #191

Clean Roll Strings

---

dist/dndbeyond_character.js
dist/fvtt_script.js
src/dndbeyond/content-scripts/character.js
src/fvtt/page-script.js

Fixes FVTT Displaying PC/NPC Names in Lowercase & Misspell for Polearm Master Bonus Attack

---

dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Implement Protector Aasimar Radiant Soul

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Affects Sharpshooter and Great Weapon Fighting

Minor damage push changes

---

dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
dist/roll20_script.js
src/common/utils.js
src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/character.js
src/roll20/content-script.js

Implement Flames of Phlegethos

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Fixes #277 - Tiebreaker Initiative doesn't work on Dev Version

KaKaRoTo suggested Tiebreaker Initiative Fix

---

dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/character.js

Implement Skill Badges on DnDBeyond

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
src/dndbeyond/base/utils.js

Removes old logic for Brutal/Savage Damage

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
src/dndbeyond/base/utils.js

Health Pane Fix

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

String addition for Damage die improperly replaced
Fixes #360

Bugfix for Polearm Master Bonus Attack and GWF

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/roll_renderer.js

Moves the processing for Chaos Bolt after resolveRolls
Allows Chaos Bolt to process the roll results properly
Fixes #344

Fix for Chaos Bolt using new resolveRolls

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/roll_renderer.js
src/dndbeyond/content-scripts/character.js
src/roll20/content-script.js

From Mythic Odysseys of Theros
Bard: College of Eloquence
https://www.dndbeyond.com/classes/bard#CollegeofEloquence
Silver Tongue
3rd-level College of Eloquence feature
You are a master at saying the right thing at the right time. When you make a Charisma (Persuasion) or Charisma (Deception) check, you can treat a d20 roll of 9 or lower as a 10.
Similar to Rogue Reliable Talent, but specific to ONLY two Skills
Fixes #327

Implement Silver Tongue

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/roll_renderer.js
src/roll20/content-script.js

Follows Chromatic Orb, in that it asks for which damage type you choose for the Spell Damage
Fixes #356

Change to "Dragon's Breath" Spell

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
src/dndbeyond/base/utils.js

Fixes Homebrew "Perfect Dice" for these options
Fixes #357

Bugfix for Brutal Critical/Savage Attacks

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/roll_renderer.js
src/roll20/content-script.js

Add missing semicolon
Fix misspelling silverTonge -> silverTongue

Bugfix: Bard - College of Eloquence Silver Tongue

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Improves parsing to split on ":" instead of ": "
Bug found & reported by n00ch on Discord

Bugfix for custom_damage

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

I don't think I saw any cleaner way to get the setting

Bugfix for Skill Badges and "Always Ask" rolls

---

dist/roll20.js
src/roll20/content-script.js

Bugfix for Rolling Hit Die (including custom die)

---

.gitignore
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/dice.js

…that should be slightly less biased.
Decided to have a go at fixing this up despite the concerted effort from the raiser of #406 to get us to ignore it forever.
This version splits 1 into equal chunks according to the dice being rolled, which probably is better?

Refactored dice rolling logic into function.

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/roll_renderer.js

Proper addition (with multiple damages):
In some cases, the damages are not added (I believe due to the logic for tripping the addition being incorrect):
Corrects to this:

Fix for adding damages in some cases

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/common/dice.js
src/common/roll_renderer.js
src/dndbeyond/base/dice.js
src/fvtt/page-script.js

Roll is a roll that contains a DicePool of all damage and attack rolls
Change non-whispered Beyond20 roll to Roll type message

Attach Roll to ChatMessage as generated for FVTT

---

dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Fixes #436
Still could use a query for the Concentration check Constitution Save
Leaving that to @kakaroto

Implement Wizard Bladesinger Bladesong

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Yet another "Natural Weapon" with a special name...

Implement proper handling of Aarakocra Talons

---

dist/dndbeyond_character.js
src/dndbeyond/base/character.js

Fix XP-based leveling Level Parsing

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Fix for Polearm Master Bonus Attack + Improved Divine Smite

Improved Divine Smite Fix

---

dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Implement Fey Wanderer: Dreadful Strikes

---

dist/astral.js
dist/astral_script.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt_script.js
dist/roll20.js
src/astral/content-script.js
src/common/roll_renderer.js
src/dndbeyond/content-scripts/character.js
src/roll20/content-script.js

Surrounding the Background Artificer - Izzet Engineer
Fixes for spell_source being Artificer * Izzet Engineer
Fixes for specially-named "Artificer Chaos Bolt"

Artificer Artillerist Background Fixes

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Simplifies and improves the Skill Badge Override Logic

Fix for DnDBeyond Skill Badge Changes

---

dist/roll20.js
src/roll20/content-script.js

Seems to have slipped last night

Fix for Beyond20RollRenderer Rolls

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Covers the Intelligence Modifier add to Concentration Constitution Saves

Addition to "Wizard Bladesong"

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Just a thought, might help the several people having issues with where to click for this.
Doesn't need to happen necessarily.

Text Clarication for Features & Traits

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Great Weapon Master should be applicable to Polearm Master Bonus attacks

Bugfix for GWM and Polearm Master Bonus Attack

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Bugfix for Artificer: Alchemical Savant

---

dist/astral.js
dist/astral_script.js
dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

I think this is a pretty fair number at least (not sure I caught all of them) of the new Tasha's stuff.

Tashas cauldron of fixes

---

dist/astral.js
dist/astral_script.js
dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Implement Eldritch Invocation: Lifedrinker

---

dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
src/dndbeyond/base/utils.js

From Tasha's Cauldron of Everything
https://www.dndbeyond.com/feats/piercer

Implement feat: Piercer

---

dist/astral.js
dist/astral_script.js
dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js

Edited the character settings to always show what class they come from + subclass and ordered them from a-z. Non-class specific settings are at the bottom.

Character subclass settings name changes + ordering

---

dist/fvtt_script.js
src/fvtt/page-script.js

Fix for not considering discarded rolls in rerolls

---

dist/fvtt_script.js
src/fvtt/page-script.js

Fix for DNDBRoll -> FVTTRoll transform

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Addition to Symbiotic Entity

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

This was already (or was recently added) on the DnDBeyond side
Fixes Fey Wanderer Ranger's "Otherworldly Glamour" #673

Purge the Wisom addition to Skill Checks

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

Mark of Detection Half-Elf: Deductive Intuition
Mark of Storm Half-Elf: Windwright's Intuition

Implement Half-Elf Variant Racial Features

---

dist/astral.js
dist/astral_script.js
dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Fixes Add +5 damage for Charger Feat as a pull down toggle #671

Implement Charger Feat

---

dist/dndbeyond_character.js
src/dndbeyond/content-scripts/character.js

In the same vein as Unarmed Strike, but ya know, named differently...

Fix for Unarmed Fighting not processing properly

---

dist/astral.js
dist/astral_script.js
dist/background.js
dist/default_popup.js
dist/dndbeyond_character.js
dist/dndbeyond_encounter.js
dist/dndbeyond_item.js
dist/dndbeyond_monster.js
dist/dndbeyond_spell.js
dist/dndbeyond_vehicle.js
dist/fvtt.js
dist/fvtt_script.js
dist/options.js
dist/popup.js
dist/roll20.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Makes it consistent with Sneak Attack (and others)

Add a toggle to Genie's Wrath

---

src/dndbeyond/base/character.js
src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/character.js

Behaves the same as Great Weapon Fighting Style

Implement Fighting Initiate - GWF Feat && Champion Fighter "Additional Fighting Style"

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

As requested on Discord by Dobber

Implement Empowered Evocation

---

src/common/settings.js

Clean-up of settings ordering

---

src/fvtt/page-script.js

Updates the Temp HP value to TempHPMax (in addition to the current TempHP field) to help keep things more consistent.

Change to FoundryVTT Temp HP Update

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Tasha's Optional Class Feature

Implement Ranger - Favored Foe

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js

Now applies to rollAction and rollSpell as well, which is the more proper implementation RAW and RAI.

Bugfix for Ranger: Gathered Swarm

---

src/dndbeyond/base/utils.js

Implement Crit Damage for Jim's Magic Missile

---

src/dndbeyond/base/monster.js

Fixes #668
(Might break everything else, I'm bad at Regex)

Bugfix for monster attack parsing

---

src/dndbeyond/base/monster.js

Implement Minus Sign fix for NPC Sheets

---

src/common/settings.js

Thanks to fireboy72 on Discord for spotting this

Default Hotkey Fix

---

src/common/roll_renderer.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

DnDBeyond now natively supports Disciple of Life

Removal of Cleric: Disciple of Life Handling

---

src/dndbeyond/content-scripts/character.js

Fix for Tool Rolling Proficiency Assignment

---

src/dndbeyond/content-scripts/character.js

Covers particularly "Cook's Utensils"

Add Utensils check in finding if Item is a Tool

---

src/dndbeyond/content-scripts/character.js

Matches Absorb Elements + Hunter's Mark Handling (pare down to 1 Damage).

Special Handling for Spirit Guardians

---

src/dndbeyond/content-scripts/character.js

Small fix for the Parry and Rally Maneuvers for Fighter
#638

Fix for issue 638 - Fighter Maneuvers

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Add support for Ranger: Natural Explorer

---

src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/character.js

Fix Brutal Critical for Perfect Rolls Hombrew Crit

---

src/common/roll_renderer.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Implement Bard College of Spirits: Spiritual Focus

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Adds +2 to all saving throws with toggle
Used when concentrating on spells
Fixes #831

Implement Wizard: War Magic: Durable Magic

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Implement Warlock: The Undead: Grave Touched

---

src/dndbeyond/content-scripts/character.js

Basically the same as "Deductive Intuition" just above it, but for two different things.

Implement Mark of Shadow Elf Cunning Intuition

---

src/dndbeyond/content-scripts/character.js

Fixes #233
@kakaroto let me know what you think

Clean Up of Bogus Damage Types (as in "--") in rollItem

---

src/dndbeyond/content-scripts/character.js

Marks of class features

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Implement Warlock: The Celestial: Radiant Soul

---

src/common/roll_renderer.js
src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/character.js
src/roll20/content-script.js

@kakaroto Also thinking maybe we should switch Spirit Guardians to this method. Your thoughts?

Elemental spell handling

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js

Initial re-name of Handedness

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

This was UA that never made it in

Remove Paladin: Legendary Strike

---

src/common/roll_renderer.js
src/dndbeyond/content-scripts/character.js

Expansion and fix-up of #906
Fixes #911

Additional Fixes for Weapon Handedness

---

src/roll20/content-script.js

Missed in moving queries to DnDBeyond

Remove Roll20 code for Toll the Dead

---

src/roll20/content-script.js

Squashed commit of the following:
commit 541775189ad9cae6c6e1e19b785dff9b2e44d6d1
Author: Jared Griffes <jmgriffes@gmail.com>
Date:   Sun Feb 6 14:45:48 2022 -0700
Update content-script.js
commit ed0bcc60e0cb7879aaf7fc5db377ff82c1df9fd8
Author: Jared Griffes <jmgriffes@gmail.com>
Date:   Sun Feb 6 14:44:19 2022 -0700
Update content-script.js
commit d37a708ee924a77e6df8bf80b0ef13549a2a17dc
Author: Jared Griffes <jmgriffes@gmail.com>
Date:   Sun Feb 6 14:29:24 2022 -0700
Update content-script.js
commit 27c5601793e477f21c7aeab42db8852f2b1c81da
Author: Jacob Chambliss <jjchambliss@gmail.com>
Date:   Sun Feb 6 12:33:09 2022 -0600
update to check for custom dice length
commit 6e3136c6a2da062419435875126f4e309f85bc43
Author: jjchambl <jjchambliss@gmail.com>
Date:   Sun Feb 6 11:08:32 2022 -0600 …

Fixes for Digital Dice Display in Roll20

---

src/common/roll_renderer.js
src/common/settings.js
src/extension/popup.js

Adds proficiency to Death Saves at Monk level 14

Implement Monk: Diamond Soul

---

src/dndbeyond/content-scripts/character.js

Also adds Predatory Strike to Melee Attack Processing

Fix to make Predatory Strike apply Crimson Rite

---

src/fvtt/page-script.js

I think this is all this wants?

Potential Fix for FVTT 10 Chat Message Rolls

---

src/dndbeyond/content-scripts/source.js

Particularly in Lost Mine of Phandelver (for now)
Fixes #996

Fix for New Adventure "Read Aloud" Formatting

---

src/common/constants.js

Just a small update of Harpy URL in the constants file

Update Harpy URL

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Maximizes healing on Creatures with 0 HP
Toggles off after usage
https://www.dndbeyond.com/classes/cleric#GraveDomain

Implement Grave Cleric: Circle of Mortality

---

src/dndbeyond/content-scripts/character.js

Paladin: Auro of Protection not on Death Saves

---

src/dndbeyond/base/utils.js

Edge case application of GWF to Brutal Critical/Savage Attacks on a Polearm Master - Bonus Attack

Fix for Brutal/Savage + GWF + Polearm Master

---

src/dndbeyond/content-scripts/character.js
src/extension/popup.js

Minor change in how the feature was named in MotM vs VGM

Update Aasimar Radiant Soul Processing for MotM

---

src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/extension/popup.js

MotM Radiant Soul uses Proficiency Bonus instead of Level for damage

Additional Fixes for MotM Aasimar Radiant Soul

---

src/common/settings.js

fix: Corrected Death to Grave in title

---

src/common/roll_renderer.js
src/common/settings.js
src/dndbeyond/content-scripts/character.js
src/roll20/content-script.js

fix: added spaces before parens throughout app

---

src/dndbeyond/base/utils.js

This change should resolve the action rolling issues from DDB changes today. Looks like they changed the sidebar info classes.

Fix - issue with action rolls from DDB changes

---

docs/Changelog.md
docs/release_notes.md
docs/update.md

Just fixed some minor typos I noticed when I updated

---

src/dndbeyond/base/dice.js

For the DDB DOm changes to work needed to add the await for the async function the promise was not getting fulfilled once that is done it all works

added missing await for the async call

---

src/dndbeyond/base/utils.js

Just small fixes there was a typo that made the page break and I added a valid choices so only selected and valid choice is shown

fixed small typo and add valid choices to cunning strike

---

src/dndbeyond/base/character.js
src/dndbeyond/content-scripts/character.js

added tavern brawler reroll
> tavern brawler has a reroll on 1 and keep the new roll

feat: tavern brawler 2024

---

src/dndbeyond/content-scripts/character.js
src/extension/popup.js

The 2024 Halfling racial trait is called "Luck", while the 2014 racial trait is called "Lucky".
This PR adds logic to check for "Luck" racial trait in order to display the settings form and to apply the roll modification to `args.d20`.

added support for Halfling Luck 2024 feature

---

src/dndbeyond/base/extras.js

Added a bunch of fixes to ensure attributes and tidbits worked again for monster extras
HP, HP formula, AC, AC Meta, Saving throws, skills were all broken

fix: added fixes for tidbits, attributes of monster extras

---

gulpfile.js
src/dndbeyond/base/extras.js
src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/monster.js

> **NEW MOSNTER STATS:** https://www.dndbeyond.com/monsters/5194888-ancient-silver-dragon
> **OLD MONSTER STATS:** https://www.dndbeyond.com/monsters/16783-ancient-silver-dragon
> **MONSTER THAT HAVE NOT BEEN PRINTED IN 2024:** https://www.dndbeyond.com/monsters/2160329-shadrix-silverquill
> UPDATED Monster Extras ALSO -> check extra tabs for old and existing monster all have been tested

Monsters 2024

---

src/dndbeyond/base/character.js
src/dndbeyond/content-scripts/character.js

https://github.com/kakaroto/Beyond20/issues/1238
> [!WARNING]
> I did not find any issues with abilities for characters, all ability scores are being selected in desktop and mobile 
> Css classes changed now it selects the correct elements, tested both desktop and mobile

Fix: Character info fix

---

docs/support.md
src/common/dice.js
src/common/roll_renderer.js
src/common/utils.js
src/dndbeyond/base/utils.js
src/dndbeyond/content-scripts/character.js
src/extension/background.js

General Code fixes, Refactors and Typos
Cache regex
extract rogue sneak attack logic
typos
html constructors render fix
declaration of variables

Fix: general fixes and typos

---

FVTT-module/beyond20/beyond20.js
FVTT-module/beyond20/module.json
src/common/roll_renderer.js
src/common/utils.js
src/dndbeyond/content-scripts/character.js
src/dndbeyond/content-scripts/encounter.js
src/dndbeyond/content-scripts/feat.js
src/dndbeyond/content-scripts/item.js
src/dndbeyond/content-scripts/monster.js
src/dndbeyond/content-scripts/source.js
src/dndbeyond/content-scripts/spell.js
src/dndbeyond/content-scripts/vehicle.js
src/extension/background.js
src/fvtt/check-tab.js
src/fvtt/content-script.js
src/fvtt/page-script.js
src/roll20/content-script.js

This one actually enables rolls for foundry again and fixes various errors which came up the on the way.
Feel free to change whatever is needed, i will probably work the next weeks on the deprecation errors too, so the plugin will use the new foundry roll renderer.
All rolls types worked for me and were rendered correctly

Foundry v13 fix

---

src/common/roll_renderer.js
src/fvtt/page-script.js

> [!NOTE]
> Fixed issue with dice formula, added a space as suggested to ensure the modifier is not getting included in the kh dice formula
> [!NOTE]
> Fixes https://github.com/kakaroto/Beyond20/issues/1268

fix: min and operator fix

---

src/dndbeyond/content-scripts/character.js

> [!NOTE]
> so it seem i was being an idiot.... It was only a small issue that needed to be fixed everything anything started working omfg i am an idiot.

fix: item pane new css
