kakaroto/Beyond20

dist/beyond20.css, src/extension/beyond20.css
This fixes #290.
Feel free to merge or ignore and implement yourself however you'd prefer :)
=> Add workaround for background images swallowing mouse events for saving throw quickrolls.

dist/fvtt_script.js, src/fvtt/page-script.js
Converts to a newer API call from an API call deprecated in 0.6.0
Fixes #293
=> Fixes add to initiative tracker on FVTT

dist/dndbeyond_character.js, src/dndbeyond/content-scripts/character.js
Further change to accept all types of Unarmed Strikes in a more generalized way:
Unarmed Strike
Unarmed Strike - Dex (Order of Lycan Bloodhunter)
Unarmed Strike - Str (Order of Lycan Bloodhunter)
(other iterations, which there probably are)
Fixes #313
=> Fix for Crimson Rite applying to Unarmed Strikes

dist/dndbeyond_character.js, src/dndbeyond/content-scripts/character.js
Fixes #311
Rogue Soulknife (UA): Psychic Blades
3rd-level Soulknife feature
You can manifest your psionic power as shimmering blades of psychic energy. When you are about to make a melee or ranged weapon attack against a creature, you can manifest a psychic blade from your free hand and make the attack with that blade. This magic blade is a simple melee weapon with the finesse and thrown properties.
Sneak Attack
Beginning at 1st level, you know how to strike subtly and exploit a foe’s distraction. Once per turn, you can deal an extra 1d6 damage to one creature you hit with an attack if you have advantage on the attack roll. The attack must use a finesse or a ranged weapon
Sneak Attack should therefore apply to Psychic Blades (handled through rollAction).
=> Cleaner Psychic Blade Sneak Attack Fix

dist/dndbeyond_character.js, src/dndbeyond/content-scripts/character.js
Barbarian Path of the Beast Natural Weapons
Leonin-only Claws attack (will cover anything named "Claw" under rollAction)
Satyr Ram (will cover anything named "Ram" under rollAction)
Minotaur Horns (will cover anything named "Horns" under rollAction)
Centaur Hooves (will cover anything named "Hooves" under rollAction)
Fixes #330
Fixes #331
Fixes #333 
Fixes #334 
Fixes #335
=> Implement Various (specifically named) Natural Weapons

dist/dndbeyond_character.js, src/dndbeyond/content-scripts/character.js
Fixes #336
https://www.dndbeyond.com/classes/barbarian#PathoftheZealot
Divine Fury
Starting when you choose this path at 3rd level, you can channel divine fury into your weapon strikes. While you’re raging, the first creature you hit on each of your turns with a weapon attack takes extra damage equal to 1d6 + half your barbarian level. The extra damage is necrotic or radiant; you choose the type of damage when you gain this feature.
=> Implement Path of the Zealot Divine Fury

docs/faq.md
Elaborated on the process to link the D&D Beyond HP (and temp hp) to a Roll20 character sheet, and the relevant token.
=> Roll20 token hp

dist/background.js, dist/default_popup.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt.js, dist/fvtt_script.js, dist/options.js, dist/popup.js, dist/roll20.js, dist/roll20_script.js, src/common/settings.js, src/dndbeyond/base/utils.js, src/dndbeyond/content-scripts/encounter.js, src/extension/background.js, src/extension/popup.js, src/roll20/content-script.js, src/roll20/page-script.js
I've added a setting for this, which is off by default. Those interested in trying it out can enable it from the settings menu - but it might be a good idea to move this into the quick settings once it's been tested a bit. Because of this, I'm not too worried if this gets merged in.
Although this solution seems workable, there are some limitations that should be addressed;
* Ideally we shouldn't unlink tokens from the tracker. At the moment the list is replaced with a fresh version built from data in the DDB tracker.
* There's no support for hidden units - I see no such support in DDB's combat tracker anyway.
* Initiative values need to be entered by the person running the encounter. There is a way to do this automatically for monsters, but players will need manual entry.
But it's a …
=> #409 First mostly working implementation of turn tracker.

libs/css/alertify-themes/beyond20.css, libs/css/alertify.css
'Tis but a small visual fix to the "Beyond20 Quick Settings." (Tested on Chrome version 83.0.4103.116 (64 bit) on Windows 10)
=> Fix ajs-content overlapping with ajs-header in "Beyond20 Quick Settings"

dist/roll20.js, src/roll20/content-script.js
Right now, when a character condition changes for a player in a Roll20 campaign their character's name is displayed twice in the chat log. Was going to log this as an issue; but then decided to just track it down and fix it. Thanks for the great plugin; LMK if you'd prefer a different process / want me to log an issue as well.
As per Roll20 Text Chat, /em does not require a character name, only /emas for GMs wants a character name (surrounded in quotes). Update the roll20 javascript to match this (and also clean up some spacing/grammar since I happened to be there).
Tested this as both a player and GM in Roll20 Chrome; looks good to me.
As per the discussion in #499; _not_ including the other dist change due to a past src change that did not include a matching dist update to scope this PR …
=> Fix double character names in roll20 condition display

dist/astral.js, dist/astral_script.js, dist/background.js, dist/default_popup.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt.js, dist/fvtt_script.js, dist/options.js, dist/popup.js, dist/roll20.js, src/common/settings.js, src/dndbeyond/content-scripts/character.js, src/extension/popup.js
https://www.dndbeyond.com/classes/paladin#OathofConquest
Invincible Conqueror
At 20th level, you gain the ability to harness extraordinary martial prowess. As an action, you can magically become an avatar of conquest, gaining the following benefits for 1 minute:
You have resistance to all damage.
When you take the Attack action on your turn, you can make one additional attack as part of that action.
Your melee weapon attacks score a critical hit on a roll of 19 or 20 on the d20.
=> Implement Oath of Conquest: Invincible Conqueror

dist/astral.js, dist/astral_script.js, dist/background.js, dist/default_popup.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt.js, dist/fvtt_script.js, dist/options.js, dist/popup.js, dist/roll20.js, src/common/settings.js, src/dndbeyond/content-scripts/character.js, src/extension/popup.js
https://www.dndbeyond.com/classes/paladin#OathofDevotion
`As an action, you can imbue one weapon that you are holding with positive energy, using your Channel Divinity. For 1 minute, you add your Charisma modifier to attack rolls made with that weapon (with a minimum bonus of +1).`
=> Paladin Sacred Weapon

dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_monster.js, dist/dndbeyond_vehicle.js, src/dndbeyond/base/monster.js
I hate adding commit with no values in the log, so I made the changes of PR #596
I will close the other PR.
This is related to the bug seen on discord, a homebrew monster with an attack text without the default damage was giving a bad roll. Eg:
`...Hit: 2d4 + 2 ...` would be interpret as `d4+2`
because the regex took the first number as the default damage.
=> Fix RegEx for monster attack when attack default damage is missing

dist/astral.js, dist/astral_script.js, dist/background.js, dist/default_popup.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt.js, dist/fvtt_script.js, dist/options.js, dist/popup.js, dist/roll20.js, src/common/settings.js, src/roll20/content-script.js
Adds a toggle to display a Spell Description on a Spell Attack on Roll20
Logic to interact with the different Material Display Options for Roll20
Request from MaxPat on Beyond20 Discord
=> Spell Description on Spell Attack for Roll20

dist/astral_script.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt_script.js, dist/roll20.js, src/common/roll_renderer.js, src/dndbeyond/content-scripts/character.js, src/roll20/content-script.js
Fixes #546
Properly removes Critical Hit Damage and Critical Hit Damage Type (in addition to the already removed Damage/Damage Type).
This is necessary because damagesToCrits has already been called, so the Colossus Slayer Critical Hit Damage and Damage Type are already ready to go.
=> Do not query for Colossus Slayer Critical Hit

dist/astral.js, dist/astral_script.js, dist/background.js, dist/default_popup.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt.js, dist/fvtt_script.js, dist/options.js, dist/popup.js, dist/roll20.js, src/common/settings.js, src/dndbeyond/content-scripts/character.js, src/extension/popup.js
Applies to Magical Weapon Attacks
Based on weapon not containing ", Common" in item_type
May be a better way to account for "Magical Weapon" as this also does not cover infusions.
=> Implement Artificer: Battlesmith Arcane Jolt

dist/astral.js, dist/astral_script.js, dist/background.js, dist/default_popup.js, dist/dndbeyond_character.js, dist/dndbeyond_encounter.js, dist/dndbeyond_item.js, dist/dndbeyond_monster.js, dist/dndbeyond_spell.js, dist/dndbeyond_vehicle.js, dist/fvtt.js, dist/fvtt_script.js, dist/options.js, dist/popup.js, dist/roll20.js, src/common/settings.js, src/dndbeyond/content-scripts/character.js, src/extension/popup.js
Fixes #689 
Adds a toggle for Halfling Lucky
Also moves Half-Orc Savage Attacks (starts at level 1) up on the popup.js menu, to let users see it more clearly near the top.
=> Halfling lucky toggle

src/dndbeyond/base/utils.js, src/dndbeyond/content-scripts/character.js
https://www.dndbeyond.com/spells/blade-of-disaster
Attack scores a critical hit if the number on the d20 is 18 or higher.
Also implements "On a critical hit, the blade deals an extra 8d12 force damage (for a total of 12d12 force damage)."
=> Implement Critical Limit 18 for Blade of Disaster

src/dndbeyond/content-scripts/character.js
Example: Favored Foe
Shouldn't apply specifically to Hunter's Mark, because Hunter's Mark is already "extra damage" to an attack roll.
=> Stop Hunter's Mark from acquiring extra damage

src/dndbeyond/content-scripts/character.js
Also moves `Absorb Elements` and `Hunter's Mark` to the top of `handleSpecialSpells` to make sure (more with `Hunter's Mark` that they operate ONLY on their initial block.
=> Match Hunter's Mark behavior with Absorb Elements

src/dndbeyond/content-scripts/character.js
Check spell source for Empowered Evocation feature
Class: Wizard
Subclass: Evocation
Feature: Empowered Evocation (Lvl.10)
Currently checks that character has feature and spell is the proper school (Evocation), but not source of said spell. 
Feature reads:
Empowered Evocation
Beginning at 10th level, you can add your Intelligence modifier to one damage roll of any **wizard** evocation spell you cast.
Resolution:
Additionally check that spell_source includes "Wizard".
=> Add check for spell source for Empowered Evocation feature.

src/dndbeyond/content-scripts/character.js
`handleSpecialGeneralAttacks` now checks, where appropriate for `to_hit != null`
Removed redundant checks in `handleSpecialMeleeAttacks` and `handleSpecialRangedAttacks` for `to_hit != null`, as that's handled in the function calling logic
Re-ordered some parts of `handleSpecialSpells` and `handleSpecialHealingSpells` so that features which work on ALL damage types now have their chance to do so.
=> Parsing functions bugfixes

src/dndbeyond/base/monster.js
Fix for "weapon" vs "Weapon" and "attack" vs "Attack"
Example NPC: https://www.dndbeyond.com/monsters/screaming-devilkin
=> Fix for inconsistent capitalization of NPC attacks

src/dndbeyond/content-scripts/character.js
The check for Psychic Blade was outside of the OR block and thus was not
checked against the sneak attack setting; therefore resulting in always
rolling sneak attack damage when using Psychic Blade. This fix shifts
the Psychic Blade check into the main OR block.
=> Fix for Rogue Sneak Attack checks

src/dndbeyond/content-scripts/character.js
Fixes #781
The spell itself is obtuse, https://www.dndbeyond.com/spells/shadow-blade, containing no "To Hit:" or anything relevant to the attack.
Will require DnDBeyond users of the spell to create a Custom Action to cover, but works well.
=> Add handling for Shadow Blade custom action

src/dndbeyond/content-scripts/character.js
Fixes Request: Reborn's Deathless Nature #798
Reborn's Deathless Nature supplies this
Some Items supply this
All cases are covered by this detection, so long as they supply the Advantage/Disadvantage badges (as they should)
=> Implement Skill Badge Detection on Death Saves

src/dndbeyond/content-scripts/character.js
Fixes #841
This is needed because DnDBeyond recently changed all Spell Damage Types
Used to be properly Capitalized "Fire", now are all like "fire"
=> Fix for Spell Damage Types now being LowerCase

src/fvtt/page-script.js
This is due to "tempmax" being poorly documented in FoundryVTT.
Prior belief: "tempmax" = "The Maximum Temporary HP for a character"
Corrected: "tempmax" = "A temporary addition to the Maximum HP for a character"
Evidence:
https://gitlab.com/foundrynet/dnd5e/-/issues/828
Aid (inside FoundryVTT, with no DnDBeyond/Beyond20 help) should be added to TempMax
(Beyond20 already syncs a higher max HP via the "HP Max", so we shouldn't touch this)
Visual Appearance of the bars:
https://gitlab.com/foundrynet/dnd5e/-/issues/306
We want it to look like the second character in the screenshot, Temp HP overlaying the Current HP, not the 5th character in the screenshot.
=> Remove TempHPMax Syncing to FoundryVTT

src/dndbeyond/content-scripts/character.js
`prof_val` was cast as a String, causing the `mod += prof_val;` later in the code to concatenate a string rather than add Integers
=> Fix bug in Custom Skills that Query for Ability

src/common/roll_renderer.js
Brings spell into line with Chromatic Orb Handling
Fixes #860
=> Implement Damage Type Query for "Spirit Shroud" and "Destructive Wave" Spells

src/roll20/content-script.js
Fix a bug with:
1. Digital Dice: Enabled (DnDBeyond)
2. Use Digital Dice: Disabled (Beyond20 settings)
3. Force Crits: Enabled
4. Clicking the Digital Dice Damage button
Previously would fail to actually force the crit, but only for Spell Attacks.
=> Fix Digital Dice Force Crits Bug

src/common/roll_renderer.js, src/dndbeyond/base/utils.js
This seems like a proper change to the Force Critical behavior, as discussed on Discord: https://discord.com/channels/578874022968688640/579077147994488862/937516920469598248 
(there and below)
Essentially:
1. Force Criticals is wanted
2. Even with no to-hit, determine critical_damages
3. Even with no to_hit, roll the critical
I can't think of any reason at the moment this would cause issues specifically, and it fixes rolling things like Sneak Attack (with Force Critical via setting or Key Modifier) from the "Other" tab of "Actions":
=> Changes to Force Critical Behavior

src/dndbeyond/base/utils.js
There was no check on Brutal Critical/Savage Attacks applying Great Weapon Fighting. There may be a better one that this, but this is something that is available already at the point of this function.
=> Fix for Brutal Critical/Savage Attacks w/ GWF

src/dndbeyond/base/utils.js, src/roll20/content-script.js
Moves some things back into a `to_hit` check, which should actually only occur with a `to_hit`.
Fixes for Roll20 to allow the following combo:
DnDBeyond Digital Dice enabled on Character Sheet
"Use DnDBeyond Digital Dice" disabled in Beyond20 settings
To roll things like this properly:
=> Additional fixes for Critical Processing

src/dndbeyond/content-scripts/character.js
Seems to be accounted for in the DnDBeyond Site Design itself now
Current Beyond20 Behavior:
Workaround removal:
=> Remove DnDBeyond Sale/Offer Banner Workaround

libs/css/alertify-themes/beyond20.css
Set a max-width property to the ajs-dialog of 1250px; this was tested on an ultrawide 1080p monitor and a 16:9 monitor. Feel free to test and adjust the pixel value set in the beyond20.css file at the bottom. I've commented the relevant section.
=> proposed fix for width in beyond20 settings

src/dndbeyond/content-scripts/character.js
Also improves parsing for Polearm Master attacks being considered Melee, as below:
(Currently doesn't even have normal damage, but getting ahead of DnDBeyond maybe getting their crap together someday)
=> Fix Divine Smite Processing for Polearm Master Attacks

src/roll20/content-script.js
**Problem:**
When rolling with advantage/disadvantage into roll20, while using digital dice and the D&D 5E By Roll20 template, both rolls were shown in dark black. Correctly one of them should be lighter to indicate it being dropped due to the advantage/disadvantage.
Currently showing: 
Correct version for disadvantage:
**Changes summary:**
Originally attack prop `always: "1"` was being added. I added 2 special cases for when the roll is indicated to be with advantage/disadvantage and the number of rolled dice is 2 (because rolls beyond 2 are grouped into the second roll and the advantage indicator in the template is unable to process those)
=> Fix for displaying dropped dice indication for advantage/disadvantage in roll20, when using digital dice and D&D 5E By Roll20 template

src/dndbeyond/content-scripts/character.js
Fixes #159 
Blood Curse of the Eyeless appears to be the only item that needs a roll like this.
However, it appears there are a ton of Bloodhunter things not implemented. I'm hesitant to go further with it, as it's Unofficial, and there have been no requests for it, but I also like having as complete coverage as possible.
Your thoughts @kakaroto ?
=> Implement Custom Roll for Blood Curse of the Eyeless

src/dndbeyond/content-scripts/character.js
Adds the specific damage type based on the Genie type the Warlock is associated with
=> Add Specificity for Genie's Wrath Damage

src/dndbeyond/content-scripts/character.js
Original code checked to make sure that the weapon being used did not have "Common" in the `item_type`, as Arcane Jolt requires a Magic Weapon.
However, when an Artificer uses their Infusion on a weapon, the weapon still has an `item_type` of "Common", but with modified text.
This change causes the "common (requires attunement)" check to be added and done first, so it supersedes the exclusion of strictly common items.
=> Bugfix for Artificier Arcane Jolt

src/dndbeyond/base/utils.js
Vicious Weapons do an extra flat 7 Damage on attack rolls
This is similar to Swords of Sharpness:
Except DnDBeyond did not deign to implement the extra damage. This change makes the Vicious Weapons appear essentially the same as the Swords of Sharpness in rolls.
=> Implement Extra Damage from Vicious Weapons

src/common/settings.js, src/roll20/content-script.js
Fixes #1003
Looks like this (Spell Details + Spell Descriptions Enabled):
And this (Spell Details Enabled, Spell Descriptions Disabled):
=> Add Spell Details to Roll20 Spell Display

src/dndbeyond/content-scripts/character.js
Lazy setup by DnDBeyond shows all damages for each weapon
Pare down to single additional damage
Allow setting "note" on a weapon to specify damage
"note" must be set to a Damage type available to be infused on the weapon to apply (fallback is "Infused Damage")
=> Handle Dragon Wing * Ranged Weapons + Flail of Tiamat Damages

src/dndbeyond/content-scripts/character.js
Add Otherworldly Glamour to Skill Checks
Fixes #1017
https://www.dndbeyond.com/classes/ranger#FeyWanderer
```
Otherworldly Glamour
3rd-level Fey Wanderer feature
Your fey qualities give you a supernatural charm. As a result, whenever you make a Charisma check, you gain a bonus to the check equal to your Wisdom modifier (minimum of +1).
```
I read that as applying to Deception/Intimidation/Persuasion as well.
=> Remove Otherworldly Glamour from Charisma Saves

src/dndbeyond/content-scripts/character.js
`Restrained` is being spelled out as `RRestrained` on the virtual table top when updating conditions on a character sheet.
The issue stemmed from the code taking the text inside a `div` and using that as the text for the condition. However the Restrained div had 3 `divs` inside of it, one of which had an `svg` with the letter `R` in it. This updated PR takes the specific div with the desired text instead
=> Fix issue regarding the restrained condition being mispelled on the VTT

src/dndbeyond/content-scripts/character.js
DnDBeyond appears to have implemented this themselves now. Leaving the straight Charisma Check code, as they have not done that yet
Fixes #1049
=> Remove Otherworldly Glamour for Skill Checks

src/dndbeyond/base/utils.js
As discussed on Discord.
Requires rolling a 20 to trigger, so this is more sensical.
=> Change Vicious Weapon Damage to only show on Crits

manifest.json, src/generic-site/content-script.js
Not as complicated as I imagined on the extension side, really just opened the rendered-roll event listener on the dom. The allows my web application to send dom events up with roll info. Working on documenting the roll data structure in another PR.
=> allow rendered rolls to come from custom domains

src/dndbeyond/base/monster.js
Fixes #1070
Matches text for healing-based actions in monster stat blocks to allow rolling on those abilities.
=> Support for Healing NPC Attacks

src/dndbeyond/content-scripts/character.js
Adds support for the advantage granted to concentration check from the War Caster feat.
To avoid having multiple popups, if the character also has Wizard Bladesong, the response from the Bladesong confirmation will also trigger the advantage from War Caster.
=> Support for War Caster feat

docs/api.md, src/dndbeyond/content-scripts/character.js, src/dndbeyond/content-scripts/encounter.js, src/dndbeyond/content-scripts/feat.js, src/dndbeyond/content-scripts/item.js, src/dndbeyond/content-scripts/monster.js, src/dndbeyond/content-scripts/source.js, src/dndbeyond/content-scripts/spell.js, src/dndbeyond/content-scripts/vehicle.js
As described in #1130 all the custom events are missing on DnD Beyond itself, making it hard to interact with the DOM API when things like settings are important. Since I am not too familiar with Beyond20's code yet, I only added the event triggers for Beyond20_Loaded and Beyond20_NewSettings for now.
Let me know if something is wrong or missing!
=> Added Beyond20_Loaded and Beyond20_NewSettings events to DnD Beyond itself

src/extension/beyond20.css
Fixes #1129
Overrides tidbit min-width:300px which is causing the overlap between the settings button and the tidbit section. This is happening between 768px and around 812px. Chose to use CSS override due to wanting to keep in line with DDBs general approach for styling buttons at tablet width rather than going straight down to an icon. 
Testing screenshot taken using Chrome in responsive mode at 768px wide:
=> Stop settings button overlaying tidbits DDB

src/fvtt/page-script.js
In troubleshooting Beyond20 with Foundry v12, I found that the terms expect an "operator" for "OperatorTerm" terms or "number" for "NumericTerm" terms.
I'm also only adding the + OperatorTerm if the previous term isn't already an OperatorTerm and using foundry.utils.isNewerVersion when available since the global isNewerVersion is deprecated.
[Issue 1127](https://github.com/kakaroto/Beyond20/issues/1127)
=> Foundry 12 / DnD5e expects the term to have operator or number set

src/dndbeyond/content-scripts/character.js
First time doing a fix like this, hmmm there was not much we could do (that i could see) with the fact that DNDBEYOND team removed the class names from the panes saving throw and ability panes. 
So .... 
To minimise the code changes I added a class name that doesn't exist, I changed the "ct" to "b20" and modified all the code to support that, Including the injection on the document modified event.
The code i pushing works on chrome, I have not tested on other browsers.
If there is any problems or you wish not accept this pull request, it is oke, "I am not married to it".
I would not normally make changes like this, just havent had much practice with this front end stuff is a while.
Some other things can be optimised also.
Fixes; https://github.com/kakaroto/Beyond20/issues/1140 and …
=> Fixes for Saving throw, Ability, Initiative, Attacks, features and Feats

src/dndbeyond/content-scripts/character.js
character management pane also changed name and the display in vtt for the avatar was missing.
Added character panel support again that was missing, the display in vtt button
had to add a different way to identify the pane since it is a pane that does not have a header (no title) to select on like all other panes. But it should be oke.
it works on all break points
=> added support again to avatar panel

src/dndbeyond/base/character.js
Added fix for https://github.com/kakaroto/Beyond20/issues/1164
Tested in chrome, and mobile, tablet and desktop layouts
After changes code now correctly shows the Genie Wrath and class features are populated (Needs verifying ALL features are working, will look into on another piece of work)
Feature now Shows on list
And it is applied correctly
These might be affect (need further testing:
Protector Aasimar: Radiant Soul Damage
MotM Aasimar: Radiant Soul Damage
Cleric: Blessed Strikes
Ranger: Favored Foe
Ranger: Gathered Swarm
Warlock: The Hexblade: Hexblade's Curse
Warlock: The Undead: Grave Touched
Artificer: Battlemaster: Arcane Jolt
Barbarian: Path of the Zealot: Divine Fury
Bard: College of Whispers: Psychic blades
Bloodhunter: Crimson Rite
Cleric: Divine Strike
Fighter: Giant’s Might; …
=> Fix for Missing Class features

src/common/roll_renderer.js, src/dndbeyond/base/utils.js
Does not include Burst aspect yet
Related to -> https://github.com/kakaroto/Beyond20/issues/1163
There is an issue with dnd beyond that they are not setting the DMG types properly for high level characters.
So this PR will need to wait until it is done, dnd beyond needs to sort out their end or we have to write some code to circumvent this 
Created a forum post for this -> https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support/206716-new-spell-sorcerous-burst-dmg-types-are-incorrect
=> added support for Sorcerous Burst Dmg type selection like Chromatic Orb

src/common/roll_renderer.js
Error when using Perfect Rolls
@kakaroto Hi just did some test today and noticed that the refactor was erroring with Perfect Roll Crit rule, So I patched that by moving the code below to the beginning of the main `if` statement. I also noticed that Bursts are not getting included on the crit section, you double the roll if it is a crit which its fine all works out in the end, It might confuse people XD. Perfect Rolls need to be added to the Crit since they are not included in the doubled calculation should we add to the burst result or to crit?
```
const critRule = parseInt(character.getGlobalSetting("critical-homebrew", CriticalRules.PHB));
const doubleForCrit = is_critical && [CriticalRules.PHB, CriticalRules.HOMEBREW_REROLL, CriticalRules.HOMEBREW_MOD].includes(critRule);
```
Standard …
=> added support to the HOMEBREW_MAX crit rules

src/common/settings.js, src/dndbeyond/base/character.js, src/dndbeyond/content-scripts/character.js, src/extension/popup.js
added support for 2024 versions of feats, added settings, and fixed features options and choices as they not getting caught.
Adds more fixes for https://github.com/kakaroto/Beyond20/issues/1164
Great Weapon master 2024
New setttings
Sharpshooter 2024
Sharpshooter no longer gives extra damage
```
General Feat (Prerequisite: Level 4+, Dexterity 13+)
You gain the following benefits.
Ability Score Increase. Increase your Dexterity score by 1, to a maximum of 20.
Bypass Cover. Your ranged attacks with weapons ignore [Half Cover](https://www.dndbeyond.com/sources/basic-rules/combat#Cover) and [Three-Quarters Cover](https://www.dndbeyond.com/sources/basic-rules/combat#Cover).
Firing in Melee. Being within 5 feet of an enemy doesn’t impose Disadvantage on your attack rolls with Ranged weapons. …
```
=> added support to 2024 Great Weapon Master and Sharpshooter and small bug fixes

src/dndbeyond/content-scripts/character.js
This fixes an Issue found by **Knightfyre** from Discord
**Knightfyre** — _Today at 08:08_
Upon further testing, it seems that what it is actually doing is applying whatever the total Attack Roll Modifier is for the first/top weapon in the HIT/DC list to ALL weapon attack rolls below it.
When I have a Club that uses STR as the modifier for attack rolls as the first weapon in my list of Attack options, it applies STR  + Proficiency Bonus as the total modifier for attack rolls made with the Club and ALL weapons listed below it.
If I check the box on the Club to designate it as my Pact Weapon, it then correctly applies CHA + Proficiency to the attack rolls for the Club; however, it now applies CHA + Proficiency as the total modifier to the attack rolls of all subsequent weapons in the list. …
=> added additional selectors to fix the find to hit issue

src/dndbeyond/base/monster.js
fixed to hit regex to support 2014 and 2024 monsters 
added saving throw actions support for 2024 monsters
tested with most monsters from 2014 and counter parts in 2024
2014: https://www.dndbeyond.com/monsters/17020-sprite
2024: https://www.dndbeyond.com/monsters/4775845-sprite
2014 BEFORE change
2024 BEFORE Change
2014 creature after change
2024 creature after change
This pull requests changes the To hit regex to take into account the changes in 2024 creatures where they have `Melee Attack Roll` Instead of `Melee Weapon Attack` and also the to Hit now doesnt have `to hit` on the text anymore. Some smaller changes were made to take into account other things. But this works now for both versions.
Change the save parsing by a bit I had to split the regex into 2014 and 2024 versions and …
=> added fix for Monster actions for 2024

FVTT-module/beyond20/beyond20.js
Fixed "Create Actors" functionality by updating the Actor object to use the ownership property instead of permission, aligning with FoundryVTT v12 API changes and Actor Schema.
=> Fix for Actor Creation Issue `bug` 

src/dndbeyond/base/monster.js, src/dndbeyond/content-scripts/character.js
monster side panel css was removed
ct-monster-panel was removed, so i made the same change we have done before when a panel is changed.
There is now a b20-monster-panel class to let all the code find and get the pane
**Before change**
**After the changes side panel is now working.**
**Tested with 2024 and 2014 monsters too to ensure nothing was affected (does not seem like it has)**
=> added fix for monster side panel

src/dndbeyond/base/character.js
impacted dice injection and number of other things - rather obscure problem it was not showing on all instances
This fix is important there was friend of mine Tomo that raised an issue that his deflect missiles were not working (it was not including the dex mod and it was rolling the incorrect die)
But when using his character it was seeing the issue, this was a 2014 issue.
dndbeyond added styledcomponents to only the mod of the ability which was not getting populated
Making the mod part of the all abilities in i the character miss the mod.
This made the very niche example of "you dexterity modifier ..." fail on dice injection.
This is all working now
=> fix for ability mod not being found

src/dndbeyond/base/character.js, src/dndbeyond/content-scripts/character.js, src/extension/popup.js
Added support for the following features:
> Main fix is the text content changes from "+ your ..." to "plus your ...." so adding support for that fixed a ton of features.
- Cleric: add support for: Improved Blessed Strikes (life)
- Cleric: add support for: Radiance of the Dawn (light)
- Cleric: add support for: Warding Flare (light)
- Cleric: add support for: Improved Warding Flare (light)
- Cleric: add support for: Sear Undead (light)
- Ranger: add support for: Tireless
- Ranger: add support for: Dreadful Strikes (Gloomstalker)
- Ranger: add support for: Stalker’s Flurry (Gloomstalker)
- Monk: add Support for: Deflect Attacks and Redirect Attack
- Monk: add Support for: Hand of Harm and Healing
- Monk: add Support for: Hand of Ultimate Mercy
=> Features: Classes 2024

src/common/settings.js, src/dndbeyond/base/extras.js, src/extension/popup.js
Added Improved Lunar Radiance for Wild shape forms.
This change works on wild shape forms when the person attacks.
> https://www.dndbeyond.com/sources/dnd/phb-2024/character-classes#Level6ImprovedCircleForms
=> druid: added support for lunar radiance 2024

src/dndbeyond/base/extras.js, src/dndbeyond/base/utils.js
Just checking for spells-attack, and attack was adding bless effects to spells that should not get it.
there was no mechanical changes but to make sure there is no issues only spells with to-hit and attacks should get this effect.
> Armor of Agathys
added strong to the elements so that the Roll Initiative! is bolded correctly
=> fix: remove effects bless and bane from spells without to-hit

src/dndbeyond/content-scripts/character.js
Added hotfix for Properties from actions that were not being selected.
This is likely a change in the on how the properties are done has broken the original selector.
All actions were broken but this fix corrects that.
=> fix: reordered selector keeping old one, to fetch properties of actions

src/dndbeyond/base/utils.js
Small fix for bug introduced with spell effects,
Monsters dont have settings so when rolling STR from the monster Extra tab it was throwing an error.
fixes https://github.com/kakaroto/Beyond20/issues/1216
=> fix: added check for settings monsters dont have these

src/dndbeyond/content-scripts/character.js
Small fix for description of custom actions 
Descriptions have been changed to use styledcomponent which break the css selector.
Fixes: https://github.com/kakaroto/Beyond20/issues/1219
=> fix: changed description selector to match new styledcomponent css

docs/api.md, src/common/settings.js, src/dndbeyond/base/utils.js, src/extension/popup.js
added setting effect that allows any character of what ever version to use 2024 exhaustion rules on their rolls.
> Setting is NOT dependent on the character being a 2024 class, giving the ability for people to decide to use 2024 rules if they want it. it is turned off by default
> The following rolls are impacted: `attack`, `spell-attack`, `initiative`, `ability`, `saving-throw`, `skill`, `death-save`. The Effect is shown in the effects list displaying the level of exhaustion.
> Ability checks, Skills, Initiative and Death Saves
> Attacks and Spell Attacks
=> feature: added support to exhaustion rules from 2024/2014

src/dndbeyond/base/utils.js
DND Beyond when they set up the new cantrip sorcerous burst they set the damage values incorrectly
> We use the properties of the spell to show which dmg type the person wants, this fix will use the first damage value which is the correct one and apply it to all damage types.
#
> [!IMPORTANT]
> There is NO check to see if the first number if the highest, this is simple fix to set all values the same. it relies on dndbeyond damage values to be correct.
=> fix: fixing dndbeyond incorrect sorcerous burst damage values

src/dndbeyond/base/utils.js
This checks if the formula we parsed ends in "+" then check if the sibling node is a modifier and adds it to the formula (removing the sibling node entirely)
This is how it looks in ddb originally:
=> Fix support for steel defender formula

src/dndbeyond/base/character.js
> the feat selection was not working, and to avoid using substrings, i have changed it to look for the entire feat plus selection
=> fix: added small fix to select the correct feat for gwf

src/dndbeyond/base/character.js, src/dndbeyond/content-scripts/character.js
> Fixes: https://github.com/kakaroto/Beyond20/issues/1234
> hp sync now works both in destop and mobile
> side panel now works again
> Fixed death saving throws, added roll dice back
=> fix: Hp syncing and death saving throws

src/dndbeyond/content-scripts/character.js
> GWM 2024 now supports ranged weapons with the heavy property  - Longbow and Heavy Crossbow
> there is not change here But just wanted to clearly say gwm will also apply with sneak or sneak works in ranged weapons also
=> feature: added support for gwm 2024 ranged weapons with heavy property

src/extension/popup.js
Devotion Paladin's Sacred Weapon is not populating in the options window.
This is because it's coming through as a Class Feature and as "Channel Divinity: Channel Divinity: Sacred Weapon"
This change listens for that instead.
Testing with the change...it now shows.
=> Fix Sacred Weapon

src/extension/popup.js
> [!NOTE]
> related to https://github.com/kakaroto/Beyond20/pull/1249
Added check for feature in different classes 2014 or 2024
> [!IMPORTANT]
> 2014 Subclass features have different names and setups depending on which base class you are using - paladin 2014 shows the feature completely different when used in 2024 paladin.
=> fix: added further fix resolve 2014/2024 differences

src/dndbeyond/base/character.js
> DNDBEYOND changed all the reference names for the 2024 books, they no longer make use of free-rules, features have been split between br-2024 (basic rules) and PHB-2024 etc
> [!IMPORTANT]
> This broke few features that we have 2014 versions and 2024 ones - like gwf
> testing character -> https://www.dndbeyond.com/characters/140676629
=> fix: change reference check for 2024 features

options.css, src/common/settings.js, src/dndbeyond/base/utils.js, src/dndbeyond/content-scripts/character.js
> [!WARNING]
> Hi @kakaroto what do you think about this? I made it as separate setting because i didnt want to have to deal with merging of settings from stored character settings already etc, and i didnt want to create another setting type, so i opted to add the "lock" setting to the bool option types as a reference to another setting that is not displayed separately. see this ticket as reference for the feature - https://github.com/kakaroto/Beyond20/issues/1241
> [!IMPORTANT]
> Code is not optimized yet just wanted to get you to give an eyeball at it
> Padlock for options, adds a padlock to certain settings that tells beyond 20 to ignore the reverting of the settings after an action was taken, example SNEAK ATTACK
> Some users suggested that they would like to use the sneak attack …
=> feature: added support for locking checkboxes

src/dndbeyond/base/utils.js, src/dndbeyond/content-scripts/character.js
> [!NOTE]
> Fixes: https://github.com/kakaroto/Beyond20/issues/1251 
> Added the int mod protective field is a min of 1 roll
=> fix: Psionic skills

FVTT-module/beyond20/beyond20.css, FVTT-module/beyond20/beyond20.js, src/extension/beyond20.css, src/fvtt/page-script.js
This pull request incorporates the changes from the foundry-v13-fix branch.
All deprecated API (I found) calls have been replaced with their modern Foundry equivalents and adjusted as needed.
To preserve backward-compatibility wherever possible, I’ve declared a few globals.
Known issue: Tooltips in chat combat messages are still being clipped.
=> Foundry v13 deprecation errors

src/dndbeyond/content-scripts/character.js
> [!NOTE]
> Fix for https://github.com/kakaroto/Beyond20/issues/1276
Only needed a check to ensure it was an attack action and not item action.
=> fix: psy warrior attacks

src/dndbeyond/base/utils.js
> [!NOTE]
> fixes  https://github.com/kakaroto/Beyond20/issues/1290
=> fix: sorcerous burst custom dmg
